### ISSUE TITLE
Plans to support .NET Core?

### ISSUE THREAD

**Issue by angelinos** [mattgenious/RechargeSharp#2]

**Comment by mattgenious** [comment]
Hi sorry for the super slow reply, I must've missed the notification.
I use the library in .NET Core daily, as it is targeted to .NETStandard 2.1 it should work with .NET Core 3.0 and up.
Is it a specific version of .NET Core you mean, if you mean 1.x I don't think I will make that but if you mean 2.x I could explore a version targeted at .NETStandard 2.0 to allow for that.

**Comment by mattgenious** [comment]
As it was quite easy to downgrade the implementation a little without sacrificing anything it now targets .NETStandard 2.0, I hope that solves the issue?

**Comment by angelinos** [comment]
Good points, the project I was trying to use it with was .Net Core 2.1

**Comment by mattgenious** [comment]
The newest beta release on nuget works with .Net Core 2.1 👍👍👍

**Comment by angelinos** [comment]
this is what I'm getting now

> Restoring packages for xyz.csproj...
NU1605: Detected package downgrade: Microsoft.Extensions.Http from 3.1.2 to 2.1.1. Reference the package directly from the project to select a different version. 
 xyz -> RechargeSharp 4.1.0-beta.1 -> Microsoft.Extensions.Http (>= 3.1.2) 
 xyz -> Microsoft.Extensions.Http (>= 2.1.1)
Package restore failed. Rolling back package changes for 'xyz'.
Time Elapsed: 00:00:00.8339209
========== Finished ==========

**Comment by mattgenious** [comment]
Ah yeah, that's because you use the Microsoft.Extensions.Http 2.1.1 in your project and we use 3.1.2 in RechargeSharp, unfortunately that brings the requirement to .NET Core 3.1 because Microsoft.Extensions.Http 3.1.2 (and 3.1.4 which is the latest) depends on .NETCoreApp 3.1.

So in conclusion, I will not be implementing it in a version compatible with .NET Core 2.1 because I don't have time to do it, if you want to do it feel free to submit a pull request and we can make a branch and specific nuget for 2.1 compatible RechargeSharp.

Otherwise you will have to upgrade your project to .NET Core 3.1 LTS as described here 
2.1->2.2 https://docs.microsoft.com/en-us/aspnet/core/migration/21-to-22?view=aspnetcore-3.1&tabs=visual-studio
2.2 -> 3.0 https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio
3.0 -> 3.1 https://docs.microsoft.com/en-us/aspnet/core/migration/30-to-31?view=aspnetcore-3.1&tabs=visual-studio

I hope this helps in any way.

**Comment by angelinos** [comment]
got it, thank you for looking into it.
